-- Metadata for the AL loop: datasets, images, labels, rounds, the simulation
-- oracle's ground truth, and edge captures. Applied once by `al db migrate`.
--
-- Every table has a surrogate primary key `id`. Natural keys are UNIQUE
-- constraints, so retried inserts (ON CONFLICT ... DO NOTHING) stay no-ops.
-- `id` is a bigint identity, except rounds.id: a uuid, because it is also
-- the Step Functions execution name.

-- One label list per dataset. Its order is the model's output order and is
-- copied into the model manifest.
CREATE TABLE datasets (
    id          bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name        text NOT NULL UNIQUE CHECK (name ~ '^[a-z0-9][a-z0-9_-]*$'),
    labels      text[] NOT NULL CHECK (cardinality(labels) >= 2),
    created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE images (
    id          bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    dataset_id  bigint NOT NULL REFERENCES datasets (id),
    sha256      text NOT NULL CHECK (sha256 ~ '^[0-9a-f]{64}$'),
    s3_key      text NOT NULL,
    status      text NOT NULL CHECK (status IN ('pending', 'unlabeled', 'queued', 'labeled')),
    split       text NOT NULL CHECK (split IN ('train', 'val', 'test')),
    source      text NOT NULL CHECK (source IN ('seed', 'edge')),
    created_at  timestamptz NOT NULL DEFAULT now(),
    UNIQUE (dataset_id, sha256),
    -- The AL pool is train images with status 'unlabeled' (and 'queued' while
    -- they are being labeled). Val and test images are labeled at seeding and
    -- can never take another status, so they never enter the pool.
    CONSTRAINT eval_splits_stay_labeled CHECK (split = 'train' OR status = 'labeled')
);
CREATE INDEX images_pool_idx ON images (dataset_id, split, status);

CREATE TABLE rounds (
    id               uuid PRIMARY KEY,
    dataset_id       bigint NOT NULL REFERENCES datasets (id),
    mode             text NOT NULL CHECK (mode IN ('simulation', 'production')),
    -- The human-chosen selection settings from the round config YAML.
    strategy         text NOT NULL,
    strategy_cfg     jsonb NOT NULL DEFAULT '{}',
    k                integer NOT NULL CHECK (k > 0),
    seed             integer NOT NULL,
    model_version    text,
    dataset_version  text,
    status           text NOT NULL DEFAULT 'pending'
                     CHECK (status IN ('pending', 'running', 'succeeded', 'failed', 'cancelled')),
    metrics          jsonb,
    started_by       text NOT NULL,  -- Cognito username or the IAM principal of the CLI
    -- Production mode (Phase 2): the Label Studio project for this round and
    -- the task token its webhook resumes.
    label_task_token text,
    ls_project_id    integer,
    created_at       timestamptz NOT NULL DEFAULT now(),
    finished_at      timestamptz
);
-- One active round per dataset.
CREATE UNIQUE INDEX rounds_one_active_per_dataset
    ON rounds (dataset_id) WHERE status IN ('pending', 'running');

-- Labels used for training. round_id is NULL for labels that came with the
-- dataset (val and test images at seeding). An image can be relabeled in a
-- later round; (image_id, round_id) is unique so a retried merge is a no-op.
CREATE TABLE labels (
    id          bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    image_id    bigint NOT NULL REFERENCES images (id),
    round_id    uuid REFERENCES rounds (id),
    label       text NOT NULL,
    created_at  timestamptz NOT NULL DEFAULT now(),
    UNIQUE NULLS NOT DISTINCT (image_id, round_id)
);

-- Ground truth for simulation mode, read only by the oracle. Kept apart from
-- `labels` so nothing else can see a train image's label before the oracle
-- "labels" it in a round.
CREATE TABLE oracle_labels (
    id          bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    image_id    bigint NOT NULL UNIQUE REFERENCES images (id),
    label       text NOT NULL
);

-- Edge uploads (Phase 2): the app's inference result for an image it sends.
-- capture_id is generated by the app and is the retry key. image_id is set
-- once the upload has been validated and moved to raw/.
CREATE TABLE captures (
    id             bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    capture_id     uuid NOT NULL UNIQUE,
    image_id       bigint REFERENCES images (id),
    dataset_id     bigint NOT NULL REFERENCES datasets (id),
    sha256         text NOT NULL CHECK (sha256 ~ '^[0-9a-f]{64}$'),
    device_id      text NOT NULL,  -- from the Cognito JWT, never from the request body
    model_version  text NOT NULL,
    top1           text NOT NULL,
    confidence     real NOT NULL CHECK (confidence BETWEEN 0 AND 1),
    probs          jsonb NOT NULL,
    captured_at    timestamptz NOT NULL,
    created_at     timestamptz NOT NULL DEFAULT now()
);
