"""The single CDK stack for the POC.

This stack holds the core infrastructure: S3 buckets (al-data, al-models), the
SQS job queue + DLQ, the worker's IAM user, the EC2 host with its retained data
volume, SSM parameters for non-secret settings, and the Budget alert. Later
Phase 1 PRs add the al-round state machine, Lambdas and Cognito here.

Deploy-time settings come from CDK context (`cdk deploy -c key=value`):
  adminCidr     your IP as a /32; opens MLflow (5000) and Postgres (5432) to it
  workerCidr    the GPU worker's IP if it differs from adminCidr (optional)
  budgetEmail   where the Budget alert goes; no Budget is created without it
  budgetUsd     monthly budget in USD (default 20)
  instanceType  EC2 instance type (default t3.small)
  dataVolumeGb  size of the /data EBS volume (default 20)
"""

import ipaddress

from aws_cdk import (
    Acknowledgment,
    Annotations,
    CfnOutput,
    Duration,
    RemovalPolicy,
    Size,
    Stack,
    Tags,
    Validations,
)
from aws_cdk import aws_budgets as budgets
from aws_cdk import aws_ec2 as ec2
from aws_cdk import aws_iam as iam
from aws_cdk import aws_s3 as s3
from aws_cdk import aws_sqs as sqs
from aws_cdk import aws_ssm as ssm
from constructs import Construct

# SSM Parameter Store layout. deploy/ec2/write-env.sh reads the same names.
SSM_PREFIX = "/leaf-al"
SSM_DATA_BUCKET = f"{SSM_PREFIX}/buckets/data"
SSM_MODELS_BUCKET = f"{SSM_PREFIX}/buckets/models"
SSM_JOB_QUEUE_URL = f"{SSM_PREFIX}/queues/jobs-url"
# SecureString: CloudFormation cannot create these, the owner does (docs/aws-setup.md).
SSM_POSTGRES_PASSWORD = f"{SSM_PREFIX}/postgres/password"

MLFLOW_PORT = 5000
POSTGRES_PORT = 5432

# Long enough for the worker to pick a job up; it extends visibility while a
# job runs (ChangeMessageVisibility), so a crashed job reappears in 30 minutes.
JOB_VISIBILITY_TIMEOUT = Duration.minutes(30)
# Jobs wait in the queue while the GPU machine is off.
JOB_RETENTION = Duration.days(14)
JOB_MAX_RECEIVES = 3

AL2023_AMI_PARAM = "/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64"
DOCKER_COMPOSE_VERSION = "v2.29.7"
DOCKER_BUILDX_VERSION = "v0.17.1"


def _cidr(value: str | None, key: str) -> str | None:
    if not value:
        return None
    net = ipaddress.ip_network(value, strict=True)
    if net.prefixlen == 0:
        raise ValueError(f"{key} must not be open to the whole internet: {value}")
    return str(net)


class PlatformStack(Stack):
    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)
        Tags.of(self).add("project", "leaf-al-platform")

        ctx = self.node.try_get_context
        admin_cidr = _cidr(ctx("adminCidr"), "adminCidr")
        worker_cidr = _cidr(ctx("workerCidr"), "workerCidr")

        self.data_bucket = self._bucket("DataBucket", versioned=False)
        self.models_bucket = self._bucket("ModelsBucket", versioned=True)
        self.data_bucket.add_lifecycle_rule(
            id="expire-old-postgres-backups",
            prefix="backups/",
            expiration=Duration.days(30),
        )

        self.job_dlq = sqs.Queue(
            self,
            "JobDlq",
            retention_period=JOB_RETENTION,
            encryption=sqs.QueueEncryption.SQS_MANAGED,
            enforce_ssl=True,
        )
        self.job_queue = sqs.Queue(
            self,
            "JobQueue",
            visibility_timeout=JOB_VISIBILITY_TIMEOUT,
            retention_period=JOB_RETENTION,
            receive_message_wait_time=Duration.seconds(20),
            encryption=sqs.QueueEncryption.SQS_MANAGED,
            enforce_ssl=True,
            dead_letter_queue=sqs.DeadLetterQueue(
                queue=self.job_dlq, max_receive_count=JOB_MAX_RECEIVES
            ),
        )

        self._parameters()
        self.worker_user = self._worker_user()
        self._ec2_host(admin_cidr, worker_cidr)
        self._budget(ctx("budgetEmail"), float(ctx("budgetUsd") or 20))

        CfnOutput(self, "DataBucketName", value=self.data_bucket.bucket_name)
        CfnOutput(self, "ModelsBucketName", value=self.models_bucket.bucket_name)
        CfnOutput(self, "JobQueueUrl", value=self.job_queue.queue_url)
        CfnOutput(self, "JobDlqUrl", value=self.job_dlq.queue_url)
        CfnOutput(self, "WorkerUserName", value=self.worker_user.user_name)

    def _bucket(self, construct_id: str, *, versioned: bool) -> s3.Bucket:
        # Names are generated by CloudFormation (S3 names are global); the
        # stack writes them to SSM. Retained on `cdk destroy`: data is not
        # thrown away with the stack.
        rules = [
            s3.LifecycleRule(
                id="abort-incomplete-uploads",
                abort_incomplete_multipart_upload_after=Duration.days(7),
            )
        ]
        if versioned:
            rules.append(
                s3.LifecycleRule(
                    id="expire-old-versions", noncurrent_version_expiration=Duration.days(90)
                )
            )
        return s3.Bucket(
            self,
            construct_id,
            block_public_access=s3.BlockPublicAccess.BLOCK_ALL,
            object_ownership=s3.ObjectOwnership.BUCKET_OWNER_ENFORCED,
            encryption=s3.BucketEncryption.S3_MANAGED,
            enforce_ssl=True,
            versioned=versioned,
            removal_policy=RemovalPolicy.RETAIN,
            lifecycle_rules=rules,
        )

    def _parameters(self) -> None:
        for construct_id, name, value in [
            ("DataBucketParam", SSM_DATA_BUCKET, self.data_bucket.bucket_name),
            ("ModelsBucketParam", SSM_MODELS_BUCKET, self.models_bucket.bucket_name),
            ("JobQueueUrlParam", SSM_JOB_QUEUE_URL, self.job_queue.queue_url),
        ]:
            ssm.StringParameter(self, construct_id, parameter_name=name, string_value=value)

    def _param_arn(self, name: str) -> str:
        return self.format_arn(service="ssm", resource="parameter", resource_name=name.lstrip("/"))

    def _worker_user(self) -> iam.User:
        """IAM user for the local RTX 5070 worker. The access key is created by
        the owner (docs/aws-setup.md), never by CloudFormation, so it does not
        end up in stack outputs or templates."""
        user = iam.User(self, "WorkerUser")
        data, models = self.data_bucket, self.models_bucket

        user.add_to_policy(
            iam.PolicyStatement(
                sid="ConsumeJobs",
                actions=[
                    "sqs:ReceiveMessage",
                    "sqs:DeleteMessage",
                    "sqs:ChangeMessageVisibility",
                    "sqs:GetQueueAttributes",
                    "sqs:GetQueueUrl",
                ],
                resources=[self.job_queue.queue_arn],
            )
        )
        # These Step Functions actions do not support resource-level
        # permissions; the task token itself scopes what the worker can resume.
        user.add_to_policy(
            iam.PolicyStatement(
                sid="ReportTaskResults",
                actions=[
                    "states:SendTaskSuccess",
                    "states:SendTaskFailure",
                    "states:SendTaskHeartbeat",
                ],
                resources=["*"],
            )
        )
        # train/score read images and manifests, score writes predictions.
        user.add_to_policy(
            iam.PolicyStatement(
                sid="ReadTrainingData",
                actions=["s3:GetObject"],
                resources=[data.arn_for_objects("raw/*"), data.arn_for_objects("manifests/*")],
            )
        )
        user.add_to_policy(
            iam.PolicyStatement(
                sid="WriteScores",
                actions=["s3:GetObject", "s3:PutObject"],
                resources=[data.arn_for_objects("scores/*")],
            )
        )
        user.add_to_policy(
            iam.PolicyStatement(
                sid="ListDataPrefixes",
                actions=["s3:ListBucket"],
                resources=[data.bucket_arn],
                conditions={"StringLike": {"s3:prefix": ["raw/*", "manifests/*", "scores/*"]}},
            )
        )
        # MLflow clients write artifacts straight to S3 (--no-serve-artifacts).
        user.add_to_policy(
            iam.PolicyStatement(
                sid="MlflowArtifacts",
                actions=["s3:GetObject", "s3:PutObject", "s3:DeleteObject"],
                resources=[models.arn_for_objects("mlflow-artifacts/*")],
            )
        )
        user.add_to_policy(
            iam.PolicyStatement(
                sid="ListMlflowArtifacts",
                actions=["s3:ListBucket"],
                resources=[models.bucket_arn],
                conditions={"StringLike": {"s3:prefix": ["mlflow-artifacts/*"]}},
            )
        )
        user.add_to_policy(
            iam.PolicyStatement(
                sid="ReadSettings",
                actions=["ssm:GetParameter", "ssm:GetParameters"],
                resources=[
                    self._param_arn(SSM_DATA_BUCKET),
                    self._param_arn(SSM_MODELS_BUCKET),
                    self._param_arn(SSM_JOB_QUEUE_URL),
                ],
            )
        )
        return user

    def _ec2_host(self, admin_cidr: str | None, worker_cidr: str | None) -> None:
        """One instance running Postgres + MLflow (docker-compose), with all
        state on a separate EBS volume that is kept when the instance or the
        stack is deleted."""
        # Public subnet only, no NAT gateway: the VPC itself costs nothing.
        vpc = ec2.Vpc(
            self,
            "Vpc",
            max_azs=1,
            nat_gateways=0,
            subnet_configuration=[
                ec2.SubnetConfiguration(name="public", subnet_type=ec2.SubnetType.PUBLIC)
            ],
        )

        sg = ec2.SecurityGroup(
            self,
            "HostSg",
            vpc=vpc,
            description="leaf-al EC2: MLflow and Postgres from the owner and worker only",
            allow_all_outbound=True,
        )
        # No SSH: the owner connects with SSM Session Manager.
        # Postgres requires TLS (deploy/ec2/postgres/pg_hba.conf); it opens to
        # the Lambdas in the PR that adds the first one that needs it.
        sources = {c for c in (admin_cidr, worker_cidr) if c}
        for cidr in sorted(sources):
            sg.add_ingress_rule(ec2.Peer.ipv4(cidr), ec2.Port.tcp(MLFLOW_PORT), "MLflow")
            sg.add_ingress_rule(ec2.Peer.ipv4(cidr), ec2.Port.tcp(POSTGRES_PORT), "Postgres")
        if not sources:
            Annotations.of(self).add_warning_v2(
                "leaf-al:no-admin-cidr",
                "adminCidr not set: MLflow and Postgres accept no inbound traffic. "
                "Deploy with -c adminCidr=<your-ip>/32.",
            )

        role = iam.Role(
            self,
            "HostRole",
            assumed_by=iam.ServicePrincipal("ec2.amazonaws.com"),
            managed_policies=[
                iam.ManagedPolicy.from_aws_managed_policy_name("AmazonSSMManagedInstanceCore")
            ],
        )
        # write-env.sh reads the password and settings.
        role.add_to_policy(
            iam.PolicyStatement(
                actions=["ssm:GetParameter", "ssm:GetParameters"],
                resources=[self._param_arn(f"{SSM_PREFIX}/*")],
            )
        )
        role.add_to_policy(
            iam.PolicyStatement(
                actions=["kms:Decrypt"],
                resources=["*"],
                conditions={"StringEquals": {"kms:ViaService": f"ssm.{self.region}.amazonaws.com"}},
            )
        )
        # Nightly pg_dumpall (backup-postgres.sh) and restores.
        role.add_to_policy(
            iam.PolicyStatement(
                actions=["s3:PutObject", "s3:GetObject"],
                resources=[self.data_bucket.arn_for_objects("backups/*")],
            )
        )
        role.add_to_policy(
            iam.PolicyStatement(
                actions=["s3:GetObject", "s3:PutObject", "s3:DeleteObject"],
                resources=[self.models_bucket.arn_for_objects("mlflow-artifacts/*")],
            )
        )
        role.add_to_policy(
            iam.PolicyStatement(
                actions=["s3:ListBucket"],
                resources=[self.data_bucket.bucket_arn, self.models_bucket.bucket_arn],
                conditions={"StringLike": {"s3:prefix": ["backups/*", "mlflow-artifacts/*"]}},
            )
        )

        # The volume must be in the instance's AZ. Take it from the subnet, not
        # the instance, because the instance's user data refers to the volume.
        subnet = vpc.public_subnets[0]
        user_data = ec2.UserData.for_linux()
        instance = ec2.Instance(
            self,
            "Host",
            vpc=vpc,
            vpc_subnets=ec2.SubnetSelection(subnets=[subnet]),
            instance_type=ec2.InstanceType(self.node.try_get_context("instanceType") or "t3.small"),
            # Resolved by EC2 at launch, not by CloudFormation at deploy: a new
            # AMI release never replaces the running instance on `cdk deploy`.
            machine_image=ec2.MachineImage.resolve_ssm_parameter_at_launch(AL2023_AMI_PARAM),
            security_group=sg,
            role=role,
            user_data=user_data,
            require_imdsv2=True,
            associate_public_ip_address=True,
            block_devices=[
                ec2.BlockDevice(
                    device_name="/dev/xvda",
                    volume=ec2.BlockDeviceVolume.ebs(
                        16, volume_type=ec2.EbsDeviceVolumeType.GP3, encrypted=True
                    ),
                )
            ],
        )

        # cfn-lint expects a literal AMI id; resolve:ssm: is valid for RunInstances.
        Validations.of(instance).acknowledge(
            Acknowledgment(
                id="CloudFormation-Validate::E1152",
                reason="resolve:ssm: AMI id is resolved by EC2 at launch",
            )
        )

        volume = ec2.Volume(
            self,
            "DataVolume",
            availability_zone=subnet.availability_zone,
            size=Size.gibibytes(int(self.node.try_get_context("dataVolumeGb") or 20)),
            volume_type=ec2.EbsDeviceVolumeType.GP3,
            encrypted=True,
            removal_policy=RemovalPolicy.RETAIN,
        )
        Tags.of(volume).add("Name", "leaf-al-data")
        ec2.CfnVolumeAttachment(
            self,
            "DataVolumeAttachment",
            instance_id=instance.instance_id,
            volume_id=volume.volume_id,
            device="/dev/sdf",
        )

        user_data.add_commands(*_host_setup_commands(volume.volume_id))

        CfnOutput(self, "InstanceId", value=instance.instance_id)
        CfnOutput(self, "DataVolumeId", value=volume.volume_id)

    def _budget(self, email: str | None, amount_usd: float) -> None:
        if not email:
            Annotations.of(self).add_warning_v2(
                "leaf-al:no-budget-email",
                "budgetEmail not set: no Budget alert is created. "
                "Deploy with -c budgetEmail=<you@example.com>.",
            )
            return
        subscribers = [
            budgets.CfnBudget.SubscriberProperty(subscription_type="EMAIL", address=email)
        ]
        budgets.CfnBudget(
            self,
            "MonthlyBudget",
            budget=budgets.CfnBudget.BudgetDataProperty(
                budget_name="leaf-al-monthly",
                budget_type="COST",
                time_unit="MONTHLY",
                budget_limit=budgets.CfnBudget.SpendProperty(amount=amount_usd, unit="USD"),
            ),
            notifications_with_subscribers=[
                budgets.CfnBudget.NotificationWithSubscribersProperty(
                    notification=budgets.CfnBudget.NotificationProperty(
                        notification_type=kind,
                        comparison_operator="GREATER_THAN",
                        threshold=threshold,
                        threshold_type="PERCENTAGE",
                    ),
                    subscribers=subscribers,
                )
                for kind, threshold in [("ACTUAL", 80), ("FORECASTED", 100)]
            ],
        )


def _host_setup_commands(volume_id: str) -> list[str]:
    """First-boot setup: Docker + compose, cron (nightly backup), and /data on
    the retained volume.

    The volume is found by its id (Nitro exposes it as an NVMe device whose
    serial is the id), so the device name does not matter. It is formatted
    only if it has no filesystem yet: a re-attached volume keeps its data.
    """
    arch = "x86_64"
    plugins = "/usr/local/lib/docker/cli-plugins"
    gh = "https://github.com/docker"
    return [
        "set -euxo pipefail",
        "dnf install -y docker git cronie",
        f"mkdir -p {plugins}",
        f"curl -fsSL {gh}/compose/releases/download/{DOCKER_COMPOSE_VERSION}/"
        f"docker-compose-linux-{arch} -o {plugins}/docker-compose",
        f"curl -fsSL {gh}/buildx/releases/download/{DOCKER_BUILDX_VERSION}/"
        f"buildx-{DOCKER_BUILDX_VERSION}.linux-amd64 -o {plugins}/docker-buildx",
        f"chmod +x {plugins}/docker-compose {plugins}/docker-buildx",
        "systemctl enable --now docker crond",
        "usermod -aG docker ec2-user",
        f"VOL={volume_id}",
        'DEV="/dev/disk/by-id/nvme-Amazon_Elastic_Block_Store_${VOL/-/}"',
        'for i in $(seq 1 60); do [ -e "$DEV" ] && break; sleep 5; done',
        '[ -e "$DEV" ]',
        'if ! blkid "$DEV"; then mkfs.ext4 -L leaf-al-data "$DEV"; fi',
        "mkdir -p /data",
        "grep -q 'LABEL=leaf-al-data' /etc/fstab || "
        "echo 'LABEL=leaf-al-data /data ext4 defaults,nofail 0 2' >> /etc/fstab",
        "mount -a",
    ]
